#!/usr/bin/env bash

my-func() {
	echo 'ISAP'
	return 0
}

#the return code like return 300 is invalid because it must be between 0 to 255 (8 bit integer)
	 

var=$(my-func)
code=$? 

echo "outpur=$var, code=$code"



