#!/usr/bin/env bash

. ./greetings || exit 1

name='buddy'

echo "before name = $name"
greet dave
#we can do pipe line here by putting the greet dave inside  paranthesis
# { greet dave; | tr a o; } | nl

echo "after name = $name"
