#!/usr/bin/env bash

greet() (
	name=$1
	echo "hello $name"
)

goodbye() (
	name=$1
	echo "goodbye $name"
)
#since we are using this code in curly_vs_parens so we use () instead of {} so that that chunk run in its own subshell (so that it can't modify the global scope)  

#better approach is to use local variable here  --> local name=$1


if ! (return 2>/dev/null); then
	#we are being called directly
	greet boss
	goodbye client
fi
