#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'  #no color --> reset

echo -e "${GREEN}[SUCCESS]${NC} Installation complete"
echo -e "${YELLOW}[WARNING]${NC} Low disk space"
echo -e "${RED}[ERROR]${NC} Could not connect to server"
